/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type SingleLineString = string
export type RulesVariables = string

export interface RefWithCycle {
foo?: Matches
bar?: Headers
[k: string]: unknown}
export interface Matches {
matches?: Matches}
/**
 * Header features add, modify, or delete headers from the request or response.
 * 
 * https://docs.edg.io/guides/v7/performance/rules/features#headers
 */
export interface Headers {
set_response_headers?: HttpResponseHeader
add_response_headers?: HttpResponseHeader1
[k: string]: unknown}
/**
 * Set, overwrite, append, or delete one or more header(s) from the response.
 * 
 * https://docs.edg.io/guides/v7/performance/rules/features#set-response-headers
 * 
 * 
 * Example:
 * ```
 * new Router()
 *   .get('/', {
 *     headers: {
 *       "set_response_headers": {
 * 		"sports": "basketball",
 * 		"+broadcast": " ott"
 *       },
 *     }
 *   })
 * ```
 */
export interface HttpResponseHeader {
/**
 * yo yo yo
 * 
 * This interface was referenced by `HttpResponseHeader1`'s JSON-Schema definition
 * via the `patternProperty` "^[+]?[-_a-zA-Z0-9 .]+$".
 * yo yo yo
 * 
 * This interface was referenced by `HttpResponseHeader1`'s JSON-Schema definition
 * via the `patternProperty` "^(Accept-Ranges|Age|Connection|Content-Encoding|Content-Length|Content-Range|Date|Server|Trailer|Transfer-Encoding|Upgrade|Vary|Via|Warning|X-EC.*)$".
 */
[k: string]:(SingleLineString | RulesVariables)|null
}
/**
 * Adds one or more header(s) to the response. 
 * 
 * https://docs.edg.io/guides/v7/performance/rules/features#add-response-headers
 */
export interface HttpResponseHeader1 {
/**
 * yo yo yo
 * 
 * This interface was referenced by `HttpResponseHeader1`'s JSON-Schema definition
 * via the `patternProperty` "^[+]?[-_a-zA-Z0-9 .]+$".
 * yo yo yo
 * 
 * This interface was referenced by `HttpResponseHeader1`'s JSON-Schema definition
 * via the `patternProperty` "^(Accept-Ranges|Age|Connection|Content-Encoding|Content-Length|Content-Range|Date|Server|Trailer|Transfer-Encoding|Upgrade|Vary|Via|Warning|X-EC.*)$".
 */
[k: string]:(SingleLineString | RulesVariables)|null
}
